name: qr_auth
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  qr_flutter: ^4.1.0
  google_sign_in: ^6.2.1
  go_router: ^13.2.1
  injectable: ^2.3.5
  get_it: ^7.6.7
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  velocity_x: ^4.1.2
  icons_plus: ^5.0.0
  cloud_firestore: ^4.15.9
  dartz: ^0.10.1
  logger: ^2.1.0
  encrypt: ^5.0.3
  firebase_database: ^10.4.10
  uuid: ^4.3.3
  dio: ^5.4.1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.5
  mobile_scanner: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  go_router_builder: ^2.4.1
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  injectable_generator: ^2.5.1

flutter:
  uses-material-design: true
  assets:
    - .env
