// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg6xIhg5NaaceAjwqjvKG91sPO4F1umPs',
    appId: '1:56059241656:web:7b16f44686d8fa8947404d',
    messagingSenderId: '56059241656',
    projectId: 'qr-authentication-ce1d9',
    authDomain: 'qr-authentication-ce1d9.firebaseapp.com',
    databaseURL: 'https://qr-authentication-ce1d9-default-rtdb.firebaseio.com',
    storageBucket: 'qr-authentication-ce1d9.appspot.com',
    measurementId: 'G-3QGSYT92FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIGHMBspSE12RaRKoo0AxWdrODn7dp4x8',
    appId: '1:56059241656:android:cc0dba311f93def147404d',
    messagingSenderId: '56059241656',
    projectId: 'qr-authentication-ce1d9',
    databaseURL: 'https://qr-authentication-ce1d9-default-rtdb.firebaseio.com',
    storageBucket: 'qr-authentication-ce1d9.appspot.com',
  );
}
